namespace :css do

  desc "Compress css"
  task :compress do
    input = 'dev/css/bootstrap.css'
    output = '/tmp/bootstrap-min.css'
    puts "compressing #{input}", "writing to #{output}"
    cmd = "yuicompressor -o '#{output}' #{input}"
    results = %x{#{cmd}}
    puts "done", '='*50
  end

  desc "Strip css"
  task :strip do
    input_path = '/tmp/bootstrap-min.css'
    output_path = 'dev/css/bootstrap-no-single-quotes-min.css'
    puts "stripping #{input_path}", "writing to #{output_path}"
    output = File.open(output_path, 'w')
    File.open(input_path) do |input|
      while line = input.gets

        # strip single-quotes so we can assign css to var
        output.write line.gsub('\'', '"')

      end
    end
    puts "done", '='*50
  end
end

namespace :js do
  desc "Compress js libs"
  task :compress do
    output = 'dev/js/lib/min.js'
    File.delete output rescue nil
    Dir['dev/js/lib/prettify.js','dev/js/lib/lang*.js','dev/js/lib/mustache.js','dev/js/lib/jquery.cookie.js','dev/js/lib/diff_match_patch_uncompressed.js'].reject{|path| path =~ /min\.js/}.each do |input|
      cmd = "yuicompressor #{input} >> #{output}"
      puts "compressing #{input}"
      results = %x{#{cmd}}
    end
    puts "writing to #{output}"
    puts "done", '='*50
  end
end

namespace :gen do

  desc "Generate gerrit.js"
  task :once do
    puts "generating gerrit.js from"

    puts "* dev/css/bootstrap-no-single-quotes-min.css"
    css = File.readlines("dev/css/bootstrap-no-single-quotes-min.css")

    js = {}
    Dir['dev/js/lib/min.js', 'dev/js/*.js'].each do |path|
      puts "* #{path}"
      name = File.basename(path, '.js').sub('-min', '')
      js[name] = File.readlines path
    end

    templates = {}
    Dir['dev/templates/*'].each do |path|
      puts "* #{path}"
      name = File.basename path, '.mustache'
      templates[name] = File.readlines(path).map {|line| line.gsub('\'', '"').chop}
    end

    File.open('gerrit.js', 'w') do |output|
      output.write <<-END
/* ===== Generated by Rakefile (rake gen:once) ===== */
(function(){

/* ===== dev/js/lib/ ===== */
#{js['min']}

/* ===== dev/css/ ===== */
var bootstrap = '#{css}';

/* ===== dev/templates/ ===== */
var templates = {};
templates.app = '#{templates['app']}';
templates.mine = '#{templates['mine']}';
templates.change = '#{templates['change']}';
templates.search = '#{templates['search']}';
templates.diff = '#{templates['diff']}';

/* ===== dev/js/config.js ===== */
#{js['config']}

/* ===== dev/js/view.js ===== */
#{js['view']}

/* ===== dev/js/rpc.js ===== */
#{js['rpc']}

/* ===== dev/js/nav.js ===== */
#{js['nav']}

/* ===== dev/js/init.js ===== */
#{js['init']}

})();
END
    end

    puts "done", '='*50
  end

  desc 'Generate gerrit.js when dev files change'
  task :auto do
    require 'fssm'
    puts 'Monitoring dev directory (ctrl+c to quit) ...'
    FSSM.monitor('dev') do
      update { Rake::Task['gen:once'].execute }
    end
    puts "done", '='*50
  end

end

task :default => ['js:compress', 'css:strip', 'css:compress', 'gen:once']